icon: assets/logo.png
summary: An application for managing bookmarks
group: Application/Emulator
vendor: Arran Ubels
packager: Arran Ubels
packagerEmail: arran4@gmail.com
license: GPLv3
url: https://github.com/arran4/send_to_linkwarden

display_name: Send To Linkwarden

keywords:
  - Link
  - Archiving
  - Bookmarking

generic_name: Send To Linkwarden

metainfo: linux/packaging/sendtolinkwarden.appdata.xml

categories:
  - Network
  - WebBrowser
  - Archiving

startup_notify: true
