icon: assets/logo.png
summary: An application for managing bookmarks
group: Application/Emulator
vendor: Arran Ubels
packager: Arran Ubels
packagerEmail: arran4@gmail.com
license: GPLv3
url: https://github.com/arran4/linkwarden_mobile

display_name: Linkwarden Mobile

keywords:
  - Link
  - Archiving
  - Bookmarking

generic_name: Linkwarden Mobile

metainfo: linux/packaging/linkwardenmobile.appdata.xml

categories:
  - Network
  - WebBrowser
  - Archiving

startup_notify: true
