display_name: Linkwarden Mobile

icon: assets/logo.png

keywords:
  - Link
  - Archiving
  - Bookmarking

generic_name: Linkwarden Mobile

# supported mime types that can be opened using this application
# supported_mime_type:
#   - audio/mpeg

metainfo: linux/packaging/linkwardenmobile.appdata.xml

categories:
  - Network
  - WebBrowser
  - Archiving

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
# 
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
#include: []