on:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  FLUTTER_VERSION: '3.24.1'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Set up environment vars
        shell: bash
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        shell: bash
        run: |
          choco install sed make yq -y
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Build Windows Executables
        run: |
          flutter upgrade
          flutter pub get
          flutter config --enable-windows-desktop
          dart pub global activate flutter_distributor
          flutter_distributor release --name onwindows
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linkwarden_mobile-Release-Binaries
          path: dist/
          retention-days: 1

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tar clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse libunwind-dev locate patchelf gir1.2-appindicator3-0.1 libappindicator3-1 libappindicator3-dev libsecret-1-0 libjsoncpp25 libsecret-1-dev libjsoncpp-dev libnotify-bin libnotify-dev mpv libmpv-dev libsecret-1-dev libjsoncpp-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev appstream libarchive-tools 

      - name: Install AppImage Tool
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv -v appimagetool /usr/local/bin/

      - name: Set up environment vars
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          curl -sS https://webi.sh/yq | sh
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Build Linux Packages
        run: |
          flutter upgrade
          flutter pub get
          dart pub global activate flutter_distributor
          flutter_distributor release --name onlinux
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse xmlstarlet libsecret-1-dev libjsoncpp-dev

      - name: Set up environment vars
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          curl -sS https://webi.sh/yq | sh
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Build Apk
        run: |
          flutter upgrade
          flutter pub get
          dart pub global activate flutter_distributor
          flutter_distributor package --platform android --targets apk,aab

      - name: Publish Android Packages
        run: |
          flutter_distributor publish \
            --path "dist/${FLUTTER_VERSION}/linkwarden_mobile-${FLUTTER_VERSION}-android.apk" \
            --targets github \
            --github-repo-owner "${GITHUB_REPOSITORY_OWNER}" \
            --github-repo-name "${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          flutter_distributor publish \
            --path "dist/${FLUTTER_VERSION}/linkwarden_mobile-${FLUTTER_VERSION}-android.aab" \
            --targets github \
            --github-repo-owner "${GITHUB_REPOSITORY_OWNER}" \
            --github-repo-name "${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Dependencies
        run: |
          python3 -m pip install --break-system-packages setuptools
          npm install --break-system-packages -g appdmg      

      - name: Set version environment vars
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          brew install yq
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Build Macos App
        run: |
          flutter upgrade
          flutter pub get
          flutter config --enable-macos-desktop
          dart pub global activate flutter_distributor
          flutter_distributor package --platform macos --targets dmg # ,pkg TODO

      - name: Publish Mac OS X Packages
        run: |
          flutter_distributor publish \
            --path "dist/${FLUTTER_VERSION}/linkwarden_mobile-${FLUTTER_VERSION}-macos.dmg" \
            --targets github \
            --github-repo-owner "${GITHUB_REPOSITORY_OWNER}" \
            --github-repo-name "${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          #flutter_distributor publish \
          #  --path "dist/${FLUTTER_VERSION}/linkwarden_mobile-${FLUTTER_VERSION}-macos.pkg" \
          #  --targets github \
          #  --github-repo-owner "${GITHUB_REPOSITORY_OWNER}" \
          #  --github-repo-name "${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

